# Generate master summary (Markdown) and interactive visualization (HTML).

# Write path setup file (detected from master + setup files). Does not modify master or setup files.
write_path_setup_file <- function(parsed, project_path, out_dir) {
  master_path <- parsed$master_path %||% NULL
  path_roots_master <- parsed$path_roots_from_master %||% character(0)
  path_roots_setup <- parsed$path_roots_from_setup %||% character(0)
  setup_vars <- parsed$setup_vars %||% character(0)
  setup_master_files <- parsed$setup_master_files %||% character(0)
  out_path <- file.path(out_dir, "path_setup.txt")
  con <- file(out_path, open = "w")
  on.exit(close(con))
  writeLines("# Path detection (from master file and setup files; this file is generated, do not edit)", con)
  writeLines(paste0("# Project: ", project_path), con)
  writeLines("", con)
  writeLines("master_file:", con)
  writeLines(if (length(master_path) > 0 && nzchar(master_path)) master_path else "(none detected)", con)
  writeLines("", con)
  writeLines("setup_or_master_files_scanned:", con)
  if (length(setup_master_files) > 0) writeLines(paste0("  - ", setup_master_files), con) else writeLines("  (none)", con)
  writeLines("", con)
  writeLines("path_roots_from_master:", con)
  if (length(path_roots_master) > 0) writeLines(paste0("  - ", path_roots_master), con) else writeLines("  (none)", con)
  writeLines("", con)
  writeLines("path_roots_from_setup:", con)
  if (length(path_roots_setup) > 0) writeLines(paste0("  - ", path_roots_setup), con) else writeLines("  (none)", con)
  writeLines("", con)
  writeLines("setup_path_vars:", con)
  if (length(setup_vars) > 0) {
    for (n in names(setup_vars)) if (nzchar(setup_vars[n])) writeLines(paste0("  ", n, ": ", setup_vars[n]), con)
  } else writeLines("  (none)", con)
  invisible(out_path)
}

generate_master_summary <- function(graph, issues, parsed, data_info, project_path, out_dir) {
  out_path <- file.path(out_dir, "master_summary.md")
  con <- file(out_path, open = "w")
  on.exit(close(con))
  
  write_lines <- function(...) writeLines(paste(...), con)
  
  write_lines("# R Project Dependency Summary")
  write_lines("")
  write_lines("Generated by R Dependency Analyzer")
  write_lines("")
  
  # Overview
  n_r <- sum(graph$nodes$type == "r_file")
  n_data <- sum(graph$nodes$type == "data")
  n_edges <- nrow(graph$edges)
  n_issues <- nrow(issues)
  
  write_lines("## Project Overview")
  write_lines("")
  write_lines("- **R files**: ", n_r)
  write_lines("- **Data files referenced**: ", n_data)
  write_lines("- **Dependencies**: ", n_edges)
  write_lines("- **Issues detected**: ", n_issues)
  write_lines("")
  
  # File index
  write_lines("## R File Index")
  write_lines("")
  setup_file <- graph$setup_file
  if (!is.null(setup_file) && setup_file %in% names(parsed$files)) {
    setup_libs <- parsed$files[[setup_file]]$libraries
    if (length(setup_libs) > 0) {
      write_lines("**Setup libraries** (from ", basename(setup_file), "): ", paste(setup_libs, collapse = ", "))
      write_lines("")
    }
  }
  for (rel in names(parsed$files)) {
    f <- parsed$files[[rel]]
    role <- if (identical(rel, setup_file)) " [Setup]" else ""
    write_lines("### ", rel, role)
    write_lines("")
    write_lines("- **Sources**: ", paste(f$sources, collapse = ", ") %||% "(none)")
    write_lines("- **Data reads**: ", paste(f$data_reads, collapse = ", ") %||% "(none)")
    extra_libs <- setdiff(f$libraries, if (!is.null(setup_file)) parsed$files[[setup_file]]$libraries else character(0))
    if (length(extra_libs) > 0) write_lines("- **Extra libraries**: ", paste(extra_libs, collapse = ", "))
    write_lines("")
  }
  
  # Dataset index
  write_lines("## Dataset Index")
  write_lines("")
  for (i in seq_len(nrow(data_info$index))) {
    row <- data_info$index[i, ]
    write_lines("### ", row$path)
    write_lines("")
    write_lines("- **Format**: ", row$format)
    write_lines("- **Exists**: ", row$exists)
    if (!is.na(row$nrow)) write_lines("- **Rows**: ", row$nrow)
    if (!is.na(row$ncol)) write_lines("- **Columns**: ", row$ncol)
    write_lines("- **Column names**: ", substr(row$columns, 1, 200), if (nchar(row$columns) > 200) "..." else "")
    if (row$format != "dta" && nzchar(row$sample_preview)) {
      write_lines("- **Sample preview**:")
      write_lines("```")
      write_lines(substr(row$sample_preview, 1, 500))
      if (nchar(row$sample_preview) > 500) write_lines("...")
      write_lines("```")
    }
    write_lines("- **Referenced by**: ", row$from_files)
    write_lines("")
  }
  
  # Dependency matrix (simplified)
  write_lines("## Dependency Graph (Edges)")
  write_lines("")
  write_lines("| From | To | Type |")
  write_lines("|------|-----|------|")
  for (i in seq_len(nrow(graph$edges))) {
    e <- graph$edges[i, ]
    write_lines("| ", e$from, " | ", e$to, " | ", e$type, " |")
  }
  write_lines("")
  
  # Issues
  write_lines("## Issues")
  write_lines("")
  if (n_issues == 0) {
    write_lines("No issues detected.")
  } else {
    write_lines("| Severity | Type | Message |")
    write_lines("|----------|------|---------|")
    for (i in seq_len(n_issues)) {
      iss <- issues[i, ]
      write_lines("| ", iss$severity, " | ", iss$type, " | ", gsub("|", "/", iss$message, fixed = TRUE), " |")
    }
  }
  write_lines("")
  
  # Suggested execution order (if no cycles)
  write_lines("## Suggested Execution Order")
  write_lines("")
  ord <- try_topological_order(graph)
  if (length(ord) > 0) {
    for (i in seq_along(ord)) {
      write_lines(paste0(i, ". ", ord[i]))
    }
  } else {
    write_lines("Could not determine order (circular dependencies may exist).")
  }
  write_lines("")
}

`%||%` <- function(x, y) if (length(x) == 0 || all(!nzchar(x))) y else x

# Execution order: first to run first. Edge A->B in flow means A runs before B.
# Sources: caller->callee means callee runs first, so we need callee->caller for sort.
try_topological_order <- function(graph) {
  r_edges <- graph$edges[graph$edges$type %in% c("sources", "pipeline", "data_flow"), ]
  r_nodes <- graph$nodes$id[graph$nodes$type == "r_file"]
  if (nrow(r_edges) == 0) return(r_nodes)
  sort_edges <- r_edges
  src_idx <- r_edges$type == "sources"
  sort_edges[src_idx, c("from", "to")] <- r_edges[src_idx, c("to", "from")]
  if (requireNamespace("igraph", quietly = TRUE)) {
    g <- igraph::graph_from_data_frame(sort_edges[, c("from", "to")], vertices = r_nodes)
    if (igraph::is_dag(g)) {
      ord <- igraph::topological_sort(g, mode = "out")
      return(as.character(ord))
    }
  }
  adj <- split(sort_edges$to, sort_edges$from)
  in_deg <- setNames(rep(0L, length(r_nodes)), r_nodes)
  for (to in sort_edges$to) in_deg[to] <- in_deg[to] + 1L
  queue <- r_nodes[in_deg[r_nodes] == 0]
  ord <- character(0)
  while (length(queue) > 0) {
    n <- queue[1]
    queue <- queue[-1]
    ord <- c(ord, n)
    for (neigh in adj[[n]] %||% character(0)) {
      in_deg[neigh] <- in_deg[neigh] - 1L
      if (in_deg[neigh] == 0) queue <- c(queue, neigh)
    }
  }
  if (length(ord) == length(r_nodes)) ord else character(0)
}

# Single source of truth: which scripts are "used" (in execution chain) vs "unused". Used for both graph and execution order.
get_used_unused_scripts <- function(graph, parsed) {
  ord <- try_topological_order(graph)
  r_nodes <- graph$nodes$id[graph$nodes$type == "r_file"]
  if (length(ord) == 0) return(list(ord = r_nodes, used = r_nodes, unused = character(0)))
  r_edges <- graph$edges[graph$edges$type %in% c("sources", "pipeline", "data_flow"), ]
  sort_edges <- r_edges
  sort_edges[r_edges$type == "sources", c("from", "to")] <- r_edges[r_edges$type == "sources", c("to", "from")]
  sinks <- setdiff(ord, unique(sort_edges$from))
  if (length(sinks) == 0) sinks <- ord[length(ord)]
  preds_of <- split(sort_edges$from, sort_edges$to)
  used <- character(0)
  queue <- sinks
  seen <- setNames(rep(FALSE, length(ord)), ord)
  while (length(queue) > 0) {
    n <- queue[1]
    queue <- queue[-1]
    if (seen[n]) next
    seen[n] <- TRUE
    used <- c(used, n)
    preds <- preds_of[[n]]
    if (!is.null(preds)) queue <- c(queue, preds)
  }
  used <- unique(used)
  all_reads_norm <- unique(path_norm_for_group(unlist(lapply(parsed$files, function(f) f$data_reads %||% character(0)))))
  src_edges <- graph$edges[graph$edges$type == "sources", ]
  repeat {
    keep <- vapply(used, function(script) {
      is_sourced <- any(src_edges$to == script & src_edges$from %in% used)
      writes <- parsed$files[[script]]$data_writes %||% character(0)
      writes_read <- any(path_norm_for_group(writes) %in% all_reads_norm)
      is_sourced || writes_read || length(writes) == 0
    }, logical(1))
    used_new <- used[keep]
    if (length(used_new) == length(used)) break
    used <- used_new
  }
  # Exclude scripts that have no R-edges at all (completely independent) from "used"
  no_connection <- setdiff(r_nodes, c(unique(r_edges$from), unique(r_edges$to)))
  used <- setdiff(used, no_connection)
  unused <- setdiff(ord, used)
  list(ord = ord, used = used, unused = unused)
}

# Build execution order display from precomputed used/unused so it matches the dependency graph.
build_execution_order_display <- function(graph, parsed, uu) {
  ord <- uu$ord
  used <- uu$used
  unused <- uu$unused
  if (length(ord) == 0) return('<p>Could not determine (possible cycles).</p>')
  r_edges <- graph$edges[graph$edges$type %in% c("sources", "pipeline", "data_flow"), ]
  sort_edges <- r_edges
  sort_edges[r_edges$type == "sources", c("from", "to")] <- r_edges[r_edges$type == "sources", c("to", "from")]
  preds_of <- split(sort_edges$from, sort_edges$to)
  deps <- preds_of
  used_ord <- ord[ord %in% used]
  levels <- setNames(rep(NA_integer_, length(used)), used)
  for (n in used_ord) {
    preds <- deps[[n]]
    if (is.null(preds) || length(preds) == 0) {
      levels[n] <- 0L
    } else {
      pred_levels <- levels[preds]
      pred_levels <- pred_levels[!is.na(pred_levels) & is.finite(pred_levels)]
      levels[n] <- if (length(pred_levels) > 0) max(pred_levels) + 1L else 0L
    }
  }
  by_level <- split(used, levels[used])
  levs <- sort(unique(levels[is.finite(levels)]))
  step_colors <- c("#dbeafe", "#d1fae5", "#fef3c7", "#e0e7ff", "#fce7f3")
  out <- '<div class="exec-order"><p class="viz-desc">Order reflects the dependency graph. Same step = can run in parallel.</p><ol class="exec-list-steps">'
  for (lev in levs) {
    items <- by_level[[as.character(lev)]]
    step <- as.integer(lev) + 1L
    bg <- step_colors[(step - 1L) %% length(step_colors) + 1L]
    for (it in items) {
      lab <- html_esc(basename(it))
      par_note <- if (length(items) > 1) ' <span class="exec-par">(parallel)</span>' else ""
      out <- paste0(out, sprintf('<li class="exec-step" style="background:%s">%s%s</li>', bg, lab, par_note))
    }
  }
  if (length(unused) > 0) {
    out <- paste0(out, '<li class="exec-unused-wrap"><details class="exec-unused-details"><summary><strong>Not used</strong> (', length(unused), ' file', if (length(unused) != 1) "s" else "", ')</summary><ul class="exec-unused-list">')
    for (u in unused) {
      out <- paste0(out, sprintf('<li>%s</li>', html_esc(basename(u))))
    }
    out <- paste0(out, '</ul></details></li>')
  }
  paste0(out, '</ol></div>')
}

generate_visualization <- function(graph, issues, parsed, data_info, project_path, out_dir, project_name = NULL) {
  nodes <- graph$nodes
  edges <- graph$edges
  out_path <- file.path(out_dir, "dependency_graph.html")
  if (is.null(project_name) || !nzchar(project_name)) project_name <- basename(project_path)

  # Write path setup (master + setup path roots) so path detection is visible; does not modify master/setup files
  write_path_setup_file(parsed, project_path, out_dir)

  if (nrow(nodes) == 0) {
    message("No nodes to visualize.")
    return(invisible(NULL))
  }

  # Flow direction: provider -> consumer. Reverse source edges (B sources A => A flows to B)
  rev_src <- edges$type == "sources"
  flow_edges <- edges
  flow_edges[rev_src, c("from", "to")] <- edges[rev_src, c("to", "from")]

  uu <- get_used_unused_scripts(graph, parsed)
  viz_html <- build_vis_network_div(graph, issues, flow_edges, uu$used)
  exec_display <- build_execution_order_display(graph, parsed, uu)
  html <- build_full_html(parsed, data_info, graph, issues, uu$ord, exec_display, viz_html, project_path = project_path, project_name = project_name)
  writeLines(html, out_path)
  invisible(out_path)
}

# Interactive vis-network: only used scripts (same set as Execution Order). Unused are listed in Execution Order only.
build_vis_network_div <- function(graph, issues, flow_edges, used) {
  r_nodes <- used
  if (length(r_nodes) == 0) return('<div id="dep-network" style="width:100%;height:200px;background:#f9fafb;border-radius:6px;display:flex;align-items:center;justify-content:center;color:#6b7280;">No scripts in the execution chain to display.</div><p class="viz-desc">All scripts are under <strong>Not used</strong> in Execution Order below.</p>')
  r_edges <- flow_edges[flow_edges$from %in% r_nodes & flow_edges$to %in% r_nodes &
    flow_edges$type %in% c("sources", "pipeline", "data_flow"), ]
  wrong_pairs <- character(0)
  if (nrow(issues) > 0) {
    for (i in which(issues$type == "wrong_dependency")) {
      caller <- issues$from[i]
      callee <- issues$to[i]
      wrong_pairs <- c(wrong_pairs, paste(callee, caller, sep = "|"))
    }
  }
  safe_id <- function(x) {
    out <- gsub("[^a-zA-Z0-9_]", "_", x)
    if (grepl("^[0-9]", out)) out <- paste0("n", out)
    out
  }
  id_map <- setNames(vapply(r_nodes, safe_id, character(1)), r_nodes)
  id_map <- setNames(make.unique(as.character(id_map), sep = "_"), names(id_map))
  has_incoming <- unique(r_edges$to)
  has_outgoing <- unique(r_edges$from)
  independent <- setdiff(r_nodes, c(has_incoming, has_outgoing))
  node_list <- lapply(r_nodes, function(id) {
    if (id %in% independent) {
      col <- list(background = "#e5e7eb", border = "#6b7280")
      shape <- "ellipse"
    } else {
      col <- list(background = "#dbeafe", border = "#2563eb")
      shape <- "box"
    }
    list(id = id_map[id], label = basename(id), title = id, color = col, shape = shape, font = list(color = "#1f2937", size = 11))
  })
  edge_list <- lapply(seq_len(nrow(r_edges)), function(i) {
    e <- r_edges[i, ]
    from_id <- id_map[e$from]
    to_id <- id_map[e$to]
    key <- paste(e$from, e$to, sep = "|")
    color <- if (key %in% wrong_pairs) "#b91c1c" else "#64748b"
    list(from = from_id, to = to_id, color = color)
  })
  nodes_with_color <- vapply(node_list, function(n) {
    sprintf('{"id":"%s","label":"%s","title":"%s","color":{"background":"%s","border":"%s"},"shape":"%s","font":{"color":"%s","size":11}}',
      n$id, html_esc_js(n$label), html_esc_js(n$title), n$color$background, n$color$border, n$shape, n$font$color)
  }, character(1))
  nodes_json <- paste0("[", paste(nodes_with_color, collapse = ","), "]")
  default_colors <- paste0("{", paste(vapply(node_list, function(n) {
    sprintf('"%s":{"bg":"%s","border":"%s"}', n$id, n$color$background, n$color$border)
  }, character(1)), collapse = ","), "}")
  edges_json <- paste0("[", paste(vapply(edge_list, function(e) {
    sprintf('{"from":"%s","to":"%s","color":"%s"}', e$from, e$to, e$color)
  }, character(1)), collapse = ","), "]")
  sprintf(
    '<div id="dep-network" style="width:100%%;height:600px;background:#fff;border-radius:6px;"></div>
    <p class="viz-desc">Dependency graph shows only scripts in the execution chain (same as the ordered list below). Red edges = wrong dependency. Scripts not in the chain are listed under <strong>Not used</strong> in Execution Order only.</p>
    <script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
    <script>
    var nodes = new vis.DataSet(%s);
    var edges = new vis.DataSet(%s);
    var container = document.getElementById("dep-network");
    var data = { nodes: nodes, edges: edges };
    var options = {
      nodes: { font: { color: "#1f2937", size: 11 } },
      edges: { arrows: "to" },
      physics: false,
      layout: { hierarchical: { enabled: true, direction: "UD", sortMethod: "directed", levelSeparation: 320, nodeSpacing: 120, treeSpacing: 180 } }
    };
    var defaultColors = %s;
    var network = new vis.Network(container, data, options);
    network.on("selectNode", function(params) {
      var sel = params.nodes[0];
      if (!sel) return;
      var inc = edges.get().filter(function(e) { return e.to === sel; });
      var out = edges.get().filter(function(e) { return e.from === sel; });
      var providers = inc.map(function(e) { return e.from; });
      var consumers = out.map(function(e) { return e.to; });
      nodes.forEach(function(n) {
        var c = n.id === sel ? "#1e40af" : (providers.indexOf(n.id) >= 0 ? "#047857" : (consumers.indexOf(n.id) >= 0 ? "#6d28d9" : "#94a3b8"));
        nodes.update({ id: n.id, color: { background: c, border: c } });
      });
    });
    network.on("deselectNode", function() {
      nodes.forEach(function(n) {
        var d = defaultColors[n.id] || { bg: "#dbeafe", border: "#2563eb" };
        nodes.update({ id: n.id, color: { background: d.bg, border: d.border } });
      });
    });
    </script>',
    nodes_json, edges_json, default_colors
  )
}

html_esc_js <- function(x) {
  x <- gsub("\\\\", "\\\\\\\\", as.character(x))
  x <- gsub('"', '\\"', x, fixed = TRUE)
  x
}

build_r_file_index <- function(parsed, graph, setup_file, project_path = NULL) {
  r_files <- names(parsed$files)
  ord <- try_topological_order(graph)
  if (length(ord) == 0) ord <- r_files
  by_folder <- split(ord, dirname(ord))
  folder_labels <- names(by_folder)
  folder_labels[folder_labels == "."] <- "root"
  names(by_folder) <- folder_labels
  if (length(project_path) > 0 && nzchar(project_path)) {
    keep <- vapply(folder_labels, function(f) {
      if (f == "root") return(TRUE)
      full <- file.path(project_path, f)
      dir.exists(full)
    }, logical(1))
    folder_labels <- folder_labels[keep]
    by_folder <- by_folder[folder_labels]
  }
  folder_order <- order_folder_names(folder_labels)
  data_refs <- build_data_reads_display(parsed)
  out <- '<h2>File Index</h2><p class="viz-desc">Organized by folder and execution order.</p>'
  if (nzchar(data_refs$legend)) {
    out <- paste0(out, '<div class="data-legend">', data_refs$legend, '</div>')
  }
  for (folder in folder_order) {
    files <- by_folder[[folder]]
    display_folder <- if (folder == "root") "root" else basename(folder)
    out <- paste0(out, sprintf('<h3>%s</h3><table><tr><th>File</th><th>Sources</th><th>Data reads</th></tr>', html_esc(display_folder)))
    for (rel in files) {
      f <- parsed$files[[rel]]
      role <- if (identical(rel, setup_file)) " [Setup]" else ""
      reads_html <- data_refs$by_file[[rel]] %||% "(none)"
      out <- paste0(out, sprintf('<tr><td>%s%s</td><td>%s</td><td class="data-reads">%s</td></tr>',
        html_esc(basename(rel)), html_esc(role),
        html_esc(paste(f$sources, collapse = ", ") %||% "(none)"),
        reads_html))
    }
    out <- paste0(out, '</table>')
  }
  out
}

order_folder_names <- function(folders) {
  priority <- c("root", "prepare", "empirical", "build", "final", "do")
  folder_bases <- ifelse(folders == "root", "root", tolower(basename(folders)))
  folders[order(match(folder_bases, priority), na.last = TRUE)]
}

build_data_reads_display <- function(parsed) {
  all_reads <- unlist(lapply(parsed$files, function(f) f$data_reads %||% character(0)))
  if (length(all_reads) == 0) return(list(legend = "", by_file = list()))
  all_reads_norm <- path_norm_for_group(all_reads)
  counts <- table(all_reads_norm)
  common <- names(counts)[counts >= 3]
  by_file <- list()
  for (rel in names(parsed$files)) {
    reads <- parsed$files[[rel]]$data_reads %||% character(0)
    if (length(reads) == 0) {
      by_file[[rel]] <- "(none)"
      next
    }
    reads_norm <- path_norm_for_group(reads)
    parts <- vapply(seq_along(reads), function(j) {
      p <- reads[j]
      p_norm <- reads_norm[j]
      display_p <- data_path_display_label(p)
      cls <- if (p_norm %in% common) "data-ref common" else "data-ref"
      sprintf('<span class="%s" title="%s">%s</span>', cls, html_esc(display_p), html_esc(if (grepl("/", display_p)) basename(display_p) else display_p))
    }, character(1))
    by_file[[rel]] <- paste(parts, collapse = " ")
  }
  legend_parts <- if (length(common) > 0) {
    vapply(common, function(p) {
      sprintf('<span class="data-ref common" title="%s">%s</span>', html_esc(p), html_esc(basename(p)))
    }, character(1))
  } else character(0)
  legend <- if (length(legend_parts) > 0) {
    paste0('<strong>Frequently used:</strong> ', paste(legend_parts, collapse = " "), ' (hover for full path)')
  } else ""
  list(legend = legend, by_file = by_file)
}

format_issue_message <- function(iss) {
  if (iss$type == "dataset_not_used") {
    sprintf('<span class="issue-dataset">%s</span> created by <span class="issue-script">%s</span> — never read',
      html_esc(iss$to), html_esc(basename(iss$from)))
  } else if (iss$type == "file_not_used") {
    sprintf('<span class="issue-file">%s</span> — not used', html_esc(iss$from))
  } else {
    html_esc(iss$message)
  }
}

build_issues_section <- function(issues) {
  if (nrow(issues) == 0) return('<h2>Issues</h2><p class="ok">No issues detected.</p>')
  n_err <- sum(issues$severity == "error")
  n_info <- sum(issues$severity == "info")
  by_type <- split(seq_len(nrow(issues)), issues$type)
  type_labels <- c(
    wrong_dependency = "Wrong dependencies (caller sources dependency but order requires reverse)",
    missing_source = "Missing source files",
    circular_dependency = "Circular dependencies",
    file_not_used = "Files not used",
    dataset_not_used = "Datasets created but never read"
  )
  out <- '<h2>Issues</h2>'
  if (n_err > 0) {
    out <- paste0(out, sprintf('<p class="issues-summary err">%d error(s) — fix before running</p>', n_err))
  }
  if (n_info > 0) {
    out <- paste0(out, sprintf('<p class="issues-summary info">%d info — optional cleanup</p>', n_info))
  }
  type_order <- c("wrong_dependency", "missing_source", "circular_dependency", "file_not_used", "dataset_not_used")
  for (t in c(intersect(type_order, names(by_type)), setdiff(names(by_type), type_order))) {
    idx <- by_type[[t]]
    n <- length(idx)
    label <- type_labels[t] %||% t
    is_err <- issues$severity[idx[1]] == "error"
    cls <- if (is_err) "issue-group err" else "issue-group info"
    out <- paste0(out, sprintf('<details class="%s"><summary>%s (%d)</summary><ul>', cls, html_esc(label), n))
    for (i in idx) {
      iss <- issues[i, ]
      out <- paste0(out, sprintf('<li>%s</li>', format_issue_message(iss)))
    }
    out <- paste0(out, '</ul></details>')
  }
  out
}

build_dataset_index <- function(data_info, parsed) {
  idx <- data_info$index
  if (nrow(idx) == 0) return('<h2>Dataset Index</h2><p>No datasets referenced.</p>')
  norm <- function(p) path_norm_for_group(p)
  # Only include datasets that are read by at least one script (used)
  used_reads_norm <- unique(norm(unlist(lapply(parsed$files, function(f) f$data_reads %||% character(0)))))
  idx <- idx[norm(idx$path) %in% used_reads_norm, , drop = FALSE]
  if (nrow(idx) == 0) return('<h2>Dataset Index</h2><p class="viz-desc">Only datasets that are read by at least one script are listed.</p><p>No such datasets found.</p>')
  data_scan <- data_info$data_scan
  creators <- character(nrow(idx))
  for (rel in names(parsed$files)) {
    for (w in parsed$files[[rel]]$data_writes %||% character(0)) {
      i <- which(norm(idx$path) == norm(w))
      if (length(i) > 0) creators[i] <- rel
    }
  }
  idx$created_by <- creators
  path_canon <- normalize_path_canonical(idx$path)
  segments_list <- strsplit(path_canon, "/")
  top_level <- vapply(seq_along(idx$path), function(i) {
    p <- idx$path[i]
    if (!grepl("/", p)) return("raw")
    segs <- segments_list[[i]]
    if (length(segs) < 1 || !nzchar(segs[1])) return("other")
    s1 <- tolower(segs[1])
    if (s1 %in% c("data", "data_dir", "data.dir") && length(segs) >= 2)
      tolower(segs[2])
    else
      s1
  }, character(1))
  top_order <- c("raw", "build", "final", "data", "intermediate", "clean", "output", "other")
  top_level <- ifelse(top_level %in% top_order, top_level, "other")
  idx$top_level <- top_level
  # When we have a data scan, only list datasets under folders that actually exist (no "other" or non-existent parents)
  allowed_top <- if (!is.null(data_scan) && length(data_scan$top_level_folders) > 0)
    data_scan$top_level_folders else NULL
  if (!is.null(allowed_top)) {
    idx <- idx[idx$top_level %in% allowed_top, , drop = FALSE]
    if (nrow(idx) == 0) return('<h2>Dataset Index</h2><p class="viz-desc">Only datasets under folders that exist in the scanned data directory are listed. No referenced datasets found under those folders.</p>')
    path_canon <- normalize_path_canonical(idx$path)
    segments_list <- strsplit(path_canon, "/")
  }
  mid_level <- vapply(seq_along(idx$path), function(i) {
    p <- idx$path[i]
    if (!grepl("/", p)) return("no_dir")
    segs <- segments_list[[i]]
    if (length(segs) < 3) return("")
    s1 <- tolower(segs[1])
    idx_after_top <- if (s1 %in% c("data", "data_dir", "data.dir") && length(segs) >= 3) 3L else 2L
    if (length(segs) >= idx_after_top) tolower(segs[idx_after_top]) else ""
  }, character(1))
  idx$mid_level <- mid_level
  parent_key <- vapply(idx$path, function(p) {
    if (!grepl("/", p)) return("no_dir")
    d <- dirname(normalize_path_canonical(p))
    if (!nzchar(d) || d == ".") "root" else path_norm_for_group(d)
  }, character(1))
  parent_display_full <- vapply(idx$path, function(p) {
    if (!grepl("/", p)) return("(path varies)")
    d <- dirname(normalize_path_canonical(p))
    if (!nzchar(d) || d == ".") "root" else d
  }, character(1))
  parent_display_short <- vapply(seq_along(idx$path), function(i) {
    d <- parent_display_full[i]
    if (!nzchar(d) || d == "root") return("root")
    if (d == "(path varies)") return("(path varies)")
    basename(d)
  }, character(1))
  idx$parent_key <- parent_key
  idx$parent_display_full <- parent_display_full
  idx$parent_display_short <- parent_display_short
  out <- '<h2>Dataset Index</h2><p class="viz-desc">Datasets that are read by at least one script are listed below. When a data directory scan is available, section headings use only actual folder names (no made-up entries). Entries under “(path varies)” are filenames with no directory in the script (path built at runtime, e.g. from a loop).</p>'
  for (tl in top_order) {
    if (!is.null(allowed_top) && !(tl %in% allowed_top)) next
    rows_tl <- which(idx$top_level == tl)
    if (length(rows_tl) == 0) next
    tl_label <- switch(tl, raw = "Raw", build = "Build", final = "Final", data = "Data",
      intermediate = "Intermediate", clean = "Clean", output = "Output")
    if (is.null(tl_label)) tl_label <- if (tl == "other") "Other" else paste0(toupper(substring(tl, 1, 1)), substring(tl, 2))
    out <- paste0(out, sprintf('<details class="dataset-folder" open><summary><strong>%s</strong> (%d dataset%s)</summary>',
      html_esc(tl_label), length(rows_tl), if (length(rows_tl) != 1) "s" else ""))
    by_mid <- split(rows_tl, idx$mid_level[rows_tl])
    mid_order <- unique(idx$mid_level[rows_tl])
    mid_order <- mid_order[order(mid_order)]
    for (mid in mid_order) {
      rows_mid <- by_mid[[mid]]
      if (is.null(rows_mid) || length(rows_mid) == 0) next
      mid_label <- if (mid == "no_dir") "(path varies)" else if (nzchar(mid)) paste0(toupper(substring(mid, 1, 1)), substring(mid, 2)) else "Files"
      n_mid <- length(rows_mid)
      out <- paste0(out, sprintf('<details class="dataset-subfolder"><summary>%s (%d)</summary>', html_esc(mid_label), n_mid))
      by_parent <- split(rows_mid, idx$parent_key[rows_mid])
      parent_order <- unique(idx$parent_key[rows_mid])[order(unique(idx$parent_key[rows_mid]))]
      for (pk in parent_order) {
        rows <- by_parent[[pk]]
        if (is.null(rows)) next
        sub <- idx[rows, ]
        sub_display <- sub$parent_display_short[1]
        out <- paste0(out, sprintf('<h4>%s</h4>', html_esc(sub_display)))
        out <- paste0(out, '<table><tr><th>File</th><th>Status</th><th>Created by</th><th>Referenced by</th></tr>')
        for (i in seq_len(nrow(sub))) {
          row <- sub[i, ]
          ex_class <- if (row$exists) "yes" else "missing"
          ex_label <- if (row$exists) "Found" else "Missing"
          display_path <- data_path_display_label(row$path)
          short_path <- basename(display_path)
          creator <- if (nzchar(row$created_by)) basename(row$created_by) else "—"
          out <- paste0(out, sprintf('<tr><td title="%s">%s</td><td class="exists %s">%s</td><td class="creator">%s</td><td class="refs">%s</td></tr>',
            html_esc(display_path), html_esc(short_path), ex_class, ex_label, html_esc(creator), html_esc(row$from_files)))
        }
        out <- paste0(out, '</table>')
      }
      out <- paste0(out, '</details>')
    }
    out <- paste0(out, '</details>')
  }
  out
}

build_full_html <- function(parsed, data_info, graph, issues, ord, exec_display, viz_html, project_path = NULL, project_name = NULL) {
  if (is.null(project_name) || !nzchar(project_name)) project_name <- "R Project"
  n_r <- sum(graph$nodes$type == "r_file")
  n_data <- sum(graph$nodes$type == "data")
  n_edges <- nrow(graph$edges)
  n_issues <- nrow(issues)
  n_err <- sum(issues$severity == "error")
  n_info <- sum(issues$severity == "info")

  setup_file <- graph$setup_file
  setup_note <- if (!is.null(setup_file) && nzchar(setup_file)) {
    sprintf('<p class="viz-desc">Setup: %s. Scripts = R/Rmd/Stata files. Datasets = data files read by scripts (CSV, RDS, .dta, etc.).</p>', html_esc(basename(setup_file)))
  } else {
    '<p class="viz-desc">Scripts = R/Rmd/Stata files. Datasets = data files read by scripts (CSV, RDS, .dta, etc.).</p>'
  }
  overview <- sprintf(
    '<h2>Project Overview</h2><div class="overview-grid"><div class="stat"><span class="num">%d</span><span class="lbl">Scripts</span></div><div class="stat"><span class="num">%d</span><span class="lbl">Datasets referenced</span></div><div class="stat"><span class="num">%d</span><span class="lbl">Dependencies</span></div><div class="stat %s"><span class="num">%d</span><span class="lbl">Issues</span></div></div>%s',
    n_r, n_data, n_edges, if (n_err > 0) "err" else "", n_issues, setup_note)

  setup_file <- graph$setup_file
  r_index <- build_r_file_index(parsed, graph, setup_file, project_path = project_path)

  data_index <- build_dataset_index(data_info, parsed)

  issues_html <- build_issues_section(issues)

  viz_section <- paste0('<h2>Dependency Graph</h2><p class="viz-desc">Interactive: zoom and pan to navigate. Arrows show flow (provider → consumer).</p>', viz_html)
  exec_section <- paste0('<h2>Execution Order</h2>', exec_display)

  sprintf('<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>%s - Dependencies</title>
  <style>
    *{box-sizing:border-box}
    body{font-family:"Segoe UI",system-ui,-apple-system,sans-serif;margin:0;padding:32px 24px;max-width:1100px;margin:0 auto;background:#f8f9fa;color:#1a1d21;line-height:1.6;font-size:14px}
    h1{color:#111;font-size:1.4rem;font-weight:600;margin:0 0 4px}
    h2{font-size:1.05rem;color:#374151;margin:28px 0 14px;padding-bottom:8px;border-bottom:1px solid #e5e7eb;font-weight:600}
    h3{font-size:0.95rem;color:#4b5563;margin:18px 0 10px;font-weight:600}
    table{border-collapse:collapse;width:100%%;background:#fff;border-radius:8px;overflow:hidden;font-size:13px;box-shadow:0 1px 3px rgba(0,0,0,.06)}
    th,td{border:1px solid #e5e7eb;padding:10px 14px;text-align:left;vertical-align:top}
    th{background:#374151;color:#fff;font-weight:500;font-size:12px;text-transform:uppercase;letter-spacing:.03em}
    tr:nth-child(even){background:#fafafa}
    tr:hover{background:#f5f5f5}
    tr.error td{background:#fef2f2}
    .section{background:#fff;padding:24px 28px;margin:0 0 20px;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,.06)}
    .overview-grid{display:flex;gap:20px;flex-wrap:wrap;margin-top:12px}
    .stat{padding:16px 24px;background:#f3f4f6;border-radius:8px;text-align:center;min-width:90px}
    .stat .num{display:block;font-size:1.6rem;font-weight:600;color:#111}
    .stat .lbl{font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.04em;margin-top:2px}
    .stat.err .num{color:#dc2626}
    .exists.yes{color:#059669;font-weight:500}.exists.missing{color:#dc2626;font-weight:500}
    .refs{font-size:12px;color:#6b7280}
    .viz-desc{font-size:12px;color:#6b7280;margin:8px 0 12px;line-height:1.5}
    .exec-list{margin:12px 0 0 24px;padding:0}
    .exec-list li{margin:6px 0}
    .issues-summary{margin-bottom:12px;font-size:13px}
    .setup-libs{margin-bottom:14px;font-size:13px;color:#4b5563;padding:10px 14px;background:#f9fafb;border-radius:6px}
    .ok{color:#059669;font-weight:500}
    .data-legend{font-size:12px;color:#6b7280;margin-bottom:16px;padding:10px 14px;background:#f9fafb;border-radius:6px;border-left:3px solid #374151}
    .data-ref{display:inline-block;padding:2px 6px;margin:1px 2px 1px 0;background:#e5e7eb;border-radius:4px;font-size:11px;cursor:help}
    .data-ref.common{background:#dbeafe;color:#1e40af}
    .data-reads{font-size:12px}
    #dep-network{border:1px solid #e5e7eb}
    .exec-order{margin-top:8px}
    .exec-list-steps{list-style:none;padding:0;margin:8px 0 0}
    .exec-step{padding:8px 12px;margin:4px 0;border-radius:6px;border-left:3px solid rgba(0,0,0,.15)}
    .exec-par{font-size:12px;color:#6b7280}
    .exec-unused-wrap{list-style:none;margin-top:8px}
    .exec-unused-details{border:1px solid #e5e7eb;border-radius:6px;background:#f9fafb}
    .exec-unused-details summary{padding:8px 12px;cursor:pointer;font-weight:500}
    .exec-unused-list{margin:8px 0 0 20px;padding-bottom:8px}
    .graph-controls{margin-bottom:10px}
    .edge-snippet-popup{position:fixed;max-width:360px;padding:10px 12px;background:#1f2937;color:#e5e7eb;font-family:monospace;font-size:12px;border-radius:6px;box-shadow:0 4px 12px rgba(0,0,0,.3);z-index:9999;pointer-events:none;white-space:pre-wrap;word-break:break-all}
    details.issue-group{margin:10px 0;border-radius:6px;overflow:hidden}
    details.issue-group summary{cursor:pointer;padding:10px 14px;background:#f9fafb}
    details.issue-group.err summary{background:#fef2f2;border-left:3px solid #dc2626}
    details.issue-group.info summary{background:#f0f9ff;border-left:3px solid #0ea5e9}
    details.issue-group ul{margin:8px 0 0 20px;padding-bottom:12px}
    .issues-summary.err{color:#dc2626;font-weight:500}
    .issues-summary.info{color:#0ea5e9}
    details.dataset-folder{margin:8px 0;border:1px solid #e5e7eb;border-radius:6px}
    details.dataset-folder summary{padding:12px 16px;cursor:pointer;background:#f9fafb}
    details.dataset-folder summary:hover{background:#f3f4f6}
    details.dataset-subfolder{margin:6px 0 6px 12px;border:1px solid #e5e7eb;border-radius:4px}
    details.dataset-subfolder summary{padding:8px 12px;cursor:pointer;background:#fafafa;font-weight:500}
    details.dataset-subfolder summary:hover{background:#f3f4f6}
    details.dataset-folder h4{margin:14px 16px 8px;font-size:0.9rem}
    details.dataset-folder table{margin:0 16px 16px}
    .issue-dataset{color:#7c3aed;font-weight:500}
    .issue-script{color:#0d9488;font-weight:500}
    .issue-file{color:#7c3aed;font-weight:500}
  </style>
</head>
<body>
  <h1>%s - Dependency Summary</h1>
  <p style="margin:0 0 24px;color:#6b7280;font-size:13px">Generated by R Dependency Analyzer</p>
  <div class="section">%s</div>
  <div class="section">%s</div>
  <div class="section">%s</div>
  <div class="section">%s</div>
  <div class="section">%s</div>
  <div class="section">%s</div>
</body>
</html>',
    html_esc(project_name), html_esc(project_name),
    overview, issues_html, viz_section, exec_section, r_index, data_index)
}

html_esc <- function(x) {
  if (length(x) == 0) return("")
  if (length(x) == 1 && !nzchar(as.character(x))) return("")
  x <- as.character(x)
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}
