---
title: "Protected Areas and Conflicts - Code Explainer"
author: "Iddo Glass"
date: "11/03/2025"
output: html_document
---

```{r setup and packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)
```


This document explains about the code construction for the project, the various assumptions made in each section etc.

### General

The code is written (as of now) in quasi-sections. Part 1 builds the grid, parts 2 and 3 create some variables which are then used to create parts 4 and 5, etc. Hence, for example, to make a change in a variable created in part 3d, it is necessary to run 3d and all the following parts (4, all the parts of 5, etc.). Perhaps I'll try to make it more efficient later.
  
### 1 - Grid
The grid is created directly in R through sf::st_make_grid. The grid is restricted to countries in Africa using the package rnaturalearth. Hence, African island countries and islands belonging to African countries (i.e. Madagascar, or the island of Bioko in Equatorial Guinea) are included but not territories belonging to non-African countries (i.e. Cueta or the Canary Islands).

The grid is continous across country borders. The main grid used in the analysis is 0.5*0.5 degrees, meaning that the maximal area of a grid cell is 3077 km2 (roughly 55.5 km on 55.5 km around the equator). There are also many small grid cells, located around coastal areas.

The coordinate system used is ESRI:102022 (WGS 1984 Albers for Africa).

### 2 - Protected areas
The WDPA data includes both points and polygons. The exact shapes of points is unclear. Per the recommendations in the WDPA codebook, there are two main options - 1) ignore points; 2) assume that the points are the centroids of the respective protected areas and buffer around them based on the data regarding their size.
The second option was chosen here (but it could easily be altered).

Only protected areas whose status is "Designated" are taken into account. 

Some PAs in the WDPA are regarded as "buffer zones", and are treated for now as regular PAs. In practice, there are also unofficial buffer zones that are not included in the data. It may be worth removing PAs regarded as buffer zones or create buffer zones around other PAs as well to evaluate spatial spillovers. 

There are also various ways through which areas are protected. Currently, only the governance type and the IUCN designation are considered when creating separate columns (although the main analysis is performed without distincting between PAs by type).

The variable "STATUS_YR", that reflects the last year that the status of the protected area has changed, is used to indicate the establishment of a protected area. It is not entirely correct as it can also refer to a change of status (i.e. from another status to "Designated") or to be caused by a change in the area of the PA. 

The intersection of PAs and grids is considered using sf::st_intersections (based on the shp files of the WDPA). Then the area covered in each cell by protected area is computed, thereby allowing to compute the share of each cell covered by PAs in any year. The functions are computationally intensive and take quite some time to run.


### 3a - ACLED 
ACLED events are considered from the beginning of the data collection in Africa (1997). For the final analysis, the last year used is 2023.

The matching between ACLED data and the grid is based on the coordinates given in the ACLED data. For each event, it finds the nearest grid cell using st_nearest_feature. 

Following McGuirk and Nunn (2024), only events labeled as "Violence against civilians" or "Battles" are considered. The event types that are excluded are protests, riots, explosions/remote violence, and strategic developments. This can easily be modified.

The distinction between events involving state actors is done based on the variable "interaction" in the ACLED data. If at least one of the sides is a state actor (has the number 1 in the interaction code), the event is labeled as involving state. Only if neither of the sides is a state actor (i.e. interaction code 37), the event is labeled as non-state. Note - I suspect that the way this distinction is done in the McGuirk and Nunn (2024) paper is wrong, as they have a suspiciously high share of events involving non-state actors.

The distinction between events involving Jihadi actors is loosely based on McGuirk and Nunn (2024). They "identify jihadist conflict events as those for which (i) the word “jihad” is present in either the actor’s name or in the source headline or (ii) the word “Islam-” appears in the source headline and one of the actors is explicitly jihadist". In our work, it is based on the word "jihad" in the actor names or if one of the actors is part of the same list used by McGuirk and Nunn (2024). 


### 3b - Precipitation
The data was extracted in GEE (Google Earth Engine). The code is provided in the data/raw/climatic folder. It is based on IMERG_MONTHLY_V07 data of NASA and is aggregated into 0.5 on 0.5 grid cells by using scale of 55660, which roughly refers to 0.5 on 0.5 degrees around the equator in GEE. 

The csv refers to average monthly precipitation in cm in a 0.5*0.5 grid cell in Africa for any given year (the csv is a yearly value in mm, in the code it is convered into monthly average in cm to follow the McGuirk and Nunn (2024) paper). The data is available from June 2000 to mid-2024 and since a yearly sum is computed, the years 2000 and 2024 were excluded. The csv therefore refers to the years 2001-2023.

The csv yields values of centroids. Some of our grid cells do not fully allign with the centroids (there is no intersection - mainly relevant for small coastal cells). Hence, each cell in our grid receives the precipitation value of the nearest centroid (meaning some neighbouring cells, especially some coastal cells and their neighbours, have identical values).  

The values are similar the precipitation values from McGuirk and Nunn (2024), and the differences can be reviewed by comparing the values of "rain" (copied from McGuirk and Nunn (2024)) and "precipitation" (which is based on my GEE code).


### 3c - Pastoralism
Data about pastoralism was downloaded from the replication files of McGuirk and Nunn (2024). 

Due to imperfect overlap between their grid and our grid, some assumptions were needed to be made about cells that exist in our data but not in theirs (almost exclusively coastal cells). Those cells were assigned values based on the value of the nearest neighbour, up to 50km. That is a better assumption for the pastoralist values than for the precipitation values, which may be differing between coastal areas and areas a bit further away. 

The exact method through which McGuirk and Nunn (2024) assign values for neighbouring cells is explained in their paper and couldn't be easily replicated from scratch as only their final grid and values are available: "For each cell, we identify its nearest neighbor, which is the ethnic group, among all ethnic groups that border a cell’s own ethnic group, that is geographically closest to
the cell". Hence, I also copied their values regarding rain, as I couldn't easily replicate their values of rain in the neighbouring cells or in the ethnic group.


### 3d - Popoulation

The data was downloaded from the Center for International Earth Science Information Network - CIESIN - Columbia University. 2018. Gridded Population of the World, Version 4 (GPWv4): Population Count, Revision 11 - https://sedac.ciesin.columbia.edu/data/set/gpw-v4-population-count-rev11

The grid used in the dataset is somewhat different than the one used in this project. Hence, squares were drawn around each centroid given in the original population data. Then, each cell in our grid was assigned a value based on the nearest neighbour from the population data (closest grid cell) within 50km. This is still problematic (and would also happen when using other spatial joining operations, i.e. sf::st_intersection) as there could be a case of more than one cell in our grid receiving the same value - for example, cell on the coast and its neighbour. In such cases, I assumed that this population value is distributed equally across the "duplicate" cells.

The data is available for the years 2000, 2005, 2010, 2015 and 2020. A log-linear interpolation was used to fill out the values in the missing years, assuming constant population growth in each cell.

### 3e - Country, colonialism and climate zones
Each grid cell is labeled to a country based on the country that covers the largest share of the cell. Alternatively is could be done based on the country where the centroid is located. Only UN recognized countries are used for consistency, so for example Somaliland is labeled as Somalia and Western Sahara as Morocco.

The colonial origin of each country is labeled based on the Authoritarian Regimes Data Set, version 5.0, by Axel Hadenius, Jan Teorell, & Michael Wahman (2007). It was donwloaded from https://datafinder.qog.gu.se/variable/ht_colonial
The data doesn't include an origin for South Sudan (that didn't exist when the dataset was created), so it was labeled as British colony (like Sudan). The classification of Somaliland as Somalia means that also the Italian Somaliland is labaled as a British colony (like the rest of Somalia).

Climate zones are labeled based on the KÖPPEN-GEIGER classification and were  downloaded from https://koeppen-geiger.vu-wien.ac.at/present.htm
They are later labeled as tropic/dry/temperate depending on the first letter in each climate zone (A/B/C).

Data about rangers is downloaded from the package rangeRinPA which is based on Appelton et al. (2022) - https://www.nature.com/articles/s41893-022-00970-0
The public data only includes data about presence of rangers and staff in certain years and not by PA. The variable I created "ranger_per_area" uses the number of rangers as a share of the area surveyed by the authors, which may be different than the area covered by PAs in our data.


### 3f - Animals

To evaluate potential tourism, we can use the presence of large animals (i.e. the "big five game"). Data about the big five + gorillas. The data was downloaded from IUCN Red List, which include shp files of animal areas - https://www.iucnredlist.org/

Similar animals (i.e. different spieces of zebras) are grouped into a single variable. For example, African elephant and Forest Elephant were labeled together as elephants in a single variable; same for Black rhino and White Rhino which were labeled as rhino, different zebra species etc.

The matching to the grid was made based on the interesection between the area where each animal is located. I defined a grid cell as having each animal if at least 1\% of its territory has this animal. 

For each animal, the variable in the final dataset is binary. The variable "num_big_game" refers to the number of distinct "big game" animals - leopard, lion, elephant and buffalo - in a given cell. Rhinos are ignored from it as the rhino data just covers the entirety of countries that have rhinos. Other animals (i.e. giraffes, zebras, gorillaz) that may be relevant for tourism are ignored from this specific variable. 

### 3g - Mines

Uses data from "This mine is mine" by Berman et al. (2017). Their grid is somewhat different than ours, so using st_intersects to recognize whether in a given cell in our data there are mines based on their cells. There are two sets of variables - baseline variables, reflecting the values at 1997 (the beginning of our data), and time varying ones. Those that reflect baseline levels are named accordingly (i.e. mines_baseline).

### 3h - Forest cover

Forest cover in the year 2000 is extracted from GEE based on Hansen et al. (2013), using v1.11. I downloaded it based on the projection EPSG:4326, and took the centroids at a scale of 55000 (55km on 55km). The matching to cells is based on st_nearest feature, such that coastal areas for example will also have values.

### 4 + 6 - Merging 

Temporary merging of variables. (4) merges variables that were created by then. Some variables created in stage 5 (for example, tourism) are based on ones that were created before, hence there's a need to do it gradually. In practice most of the variables are not created this way so this could be adjusted.

### 5a - Tourism

Downloaded data about international tourism from the World Bank. Two indicators are used - number of arrivals, and receipts in current USD - per country. There are two versions - baseline levels (reflecting 1996) and current year (for each year).

### 5b - Ethnic similarlity 

Cacluates for each cell, whether the dominant ethnic group that resides there - as determined by McGuirk and Nunn (2024), which use Murdock's atlas (see details about the matching of McGuirk and Nunn to our grid in 3c) - also resides in the cell's neighbouring cells. For example, if for a given cell, 3 out of the 4 neighbours are dominated by the same ethnic group, then the variable representing ethnic similarity to 75\% of the neighbours will be 1. Ethnic_diff variable is created based on the opposite of ethnic similarity (created later as it can be more useful for interpretation of coefficients).  

### 5c - Ethnicity from Murdock's atlas
The ethnographic atlas dataset from Murdock "describes cultural practices for 1291 societies, ranging from societies with complex agricultural economies and political systems to small hunter-gatherer groups. The societies are globally distributed with especially good coverage of Africa and western North America."

Most of the data is obtained using the "murdock" package in r, available here - https://github.com/sboysel/murdock

As each row reflects a ethnic group and its territorial area, there are two ways to match the data to ours - by the name of the ethnic group (matching it to the names matched previously, as described in 3c and 5b), or by spatially joining the geographies from the Murdock data and ours. Accordingly, for each variable, there is _text version and _geom version, reflecting how they were joined. The values reflect the dependence on a subsistance activity - gathering, hunting, fishing, animal husbnadry or agriculture. Values go from 0 (reflecting 0-5\% dependence) to 9 (reflecting 86-100\% dependence) with 10\% intervals in between (i.e. 3 is 26-35\%). 

In addition, the variable "dominant_subsistance_activity" is downloaded from https://d-place.org/contributions/EA - different agricultural types (intensive, extensive, and type unknown) are grouped together to form "Agriculture", and values are matched by name of ethnic group.

### 5d - Birds

Data from eBird about bird watchers in Africa. For each cell in our grid, match all the observations of birds within that cell. Then, the the number of distinct viewers (as in, people who view and upload data about birds in a given location) per week/month/year is counted. The variables reflect the average levels of numbers of distinct viewers in a grid cell in a week/month/year (year is not average). Then, three variables reflect the one/two/three year lags of those variables.

There is minimal cleaning of the data, for example didn't clean by type of speices. Also, other variables can be used in the eBird data, for example about the level of effort (could be useful for differntiating between tourists and non-tourists)

Similarly, perhaps we should account for higher rate of watchers in cities/urban areas.

### 5e - Distances

This chunk calculates distances of grid cells from various locations.

##### Capitals - 
This calculates distance for each cell from the capital city of the country.

For countries with more than one effective capital, it chooses one capital (alternatively, one could create a value with the minimum distance to a "capital"). Hence, for cells in South Africa, the distance to Pretoria (the administrative capital). and not to Bloemfontein, Johannesburg, or Cape Town. For Côte d'Ivoire, the distance to Yamoussoukro is measured and not to Abidjan. 

The values reflect the minimum distance in a given cell, in, km from the capital of the country. Value of 0 indicates the capital is in the cell. In some countries, the capital is located in cells that are labelled as other countries' cells (as most of the cell is in another country's territory, see 3e).

##### Coastline - 

Takes minimal distances from some point in the cell, in km, to a coastline (the coastline, like the borders and continent, are measured in scale = "medium", which refers to 50 meters).

##### Airports -

Calculates the minimal distance from the grid cell to the nearest international airport. There are two variables, one reflecting distance to any airport, and another the distance to an international airport in the same country.

Uses airport data from two sources:

1. [OSM] World Airports - based on Open Street Map - https://data.opendatasoft.com/explore/dataset/osm-world-airports@babel/export/

In this source, several categories of airports are kept: airports labelled "large"; airports labeled as "medium airports" with "international" in their name; or specific international airports in Mozambique or Benin detected manually as international airports.

2. Our Airports - https://ourairports.com/data/

Used to compliment the OSM data regarding missing airports.

Then, several airports that were established in the last few years and have only became operational for international flights very recently (i.e. from 2022) are removed, as well as some airports that do not seem operational. Overall, six airports are removed. 

##### Cities and ports -

Uses the r package "geodata" to download tif files of cities above 1 million, 5 million, and ports labelled as "large". The mean distance of the grid (so should correspond to centroid) from a city or port, depending on each category, is then used to create the variables. 

The definition of cities seems to be of Urban areas - i.e. in Nigeria, Onitsha appears as a large city as the urban area there is very populated (>7m), while the city itself is very small (<300k).


### 5f - SPEI 

Takes values from the replication files of Harari and La Ferrara (2017). For each year, it takes the value of the nearest cell from their paper (which uses 1x1 degree cells, rather than 0.5x0.5 like us) using st_nearest_feature. Their values only go until 2011, to extend it one needs to download longer period of data (perhaps in more granular level as well). 

### 5g - iNaturalist

iNaturalist data includes observations of various flora and fauna from users. Some of those users are researchers, locals, or staff at protected areas, while many are tourists. The data used here is only observations of mammals in Africa (theoretically, to determine tourism, other animals or plants could be used as well - like the eBird data - but I focused on mammals due to the size of the data if including other forms of flora and fauna. Moreover, I assumed that tourists in Africa are more likely to label mammals then plants, for exmaple). Other flora and fauna can be added quite easily, anyway.

Observations of FOSSIL_SPECIMEN are excluded (as they're not living animals), other observations are kept - we can theoretically restrict the sample further and look only at research grade obervations. The data is used to create two types of variables.

##### Biodiversity - 

iNaturalist can be used as another source (other than IUCN) for locations of mammals. I focused on zebras, giraffes, hippos, elephants, lions, leopards and rhinos, and grouped together different kinds of species from the same family - for example, different species of zebras - except for lions and leopards who remain separate.

To exclude observations in zoos, we proxy cities to being a potential location of a zoo. Cities with more than a million people are recognized using the r package geodata (see 5e). Observations at least 10km away from a city are kept if the uncertainty about the location of an observation is until 10km, and at least 30km from a city if the uncertainty about the observation's location is below 30km. Then, the number of observations of an animal category (as it could be a species, family or some mix) is measured. If it is above a threshold (currently 3), then the animal receives a binary variable as having being spotted there.

##### Tourism -

The data can also be used as a proxy for tourism. However, for that, we need to exclude protected areas workers who may disproportionately upload observations, as well as potentially exclude researchers who stay for a long-term in the areas to detect animals (the logic was taken from Englander et al. (2024) about private protected areas, see their online appendix for reference. Hence, observations by "common observers" are excluded per year, with those comomn observers being defined as people with more than x observations in at least y months in a given year (currently, x=y=3. So observers are excluded in a given year if they have uploaded more than 3 observations for 3 different months in that year). Then, the number of distinct viewers is counted per grid cell.
