source("do/conf_biodiversity_setup.R")

df <- fread(here(cln_dir, "data_unlabeled.csv"))

label_dict <- list(
  "gid" = "Grid ID - 0.5x0.5",
  "area" = "Grid Area in km^2",
  "gid_1deg" = "Grid ID - 1x1",
  "gid_2deg" = "Grid ID - 2x2",
  "gid_3deg" = "Grid ID - 3x3",
  "gid_4deg" = "Grid ID - 4x4",
  "gid_5deg" = "Grid ID - 5x5",
  "gid_10deg" = "Grid ID - 10x10",
  "year" = "Year",
  "rain" = "Rain from McGuirk and Nunn (2024)",
  "nbor_rain" = "Rain at the neighbouring cell - from McGuirk and Nunn (2024)",
  "ethnic_rain" = "Rain at the ethnic group - from McGuirk and Nunn (2024)",
  "thp_power_share" = "Power Share for transhumant-pastoralists (country-year) - from McGuirk and Nunn (2024)",
  "ethnic" = "Dominant ethnic group - from McGuirk and Nunn (2024)",
  "precipitation" = "Rain - computed from IMERG_MONTHLY_V07",
  "Rhino" = "Dummy variable for presence of rhinos in cell",
  "Leopard" = "Dummy variable for presence of leopards in cell (IUCN)",
  "Cape.Buffalo" = "Dummy variable for presence of cape buffalos in cell (IUCN)",
  "African.Elephant" = "Dummy variable for presence of African elephants in cell (IUCN)",
  "Lion" = "Dummy variable for presence of lions in cell (IUCN)",
  "Forest.Elephant" = "Dummy variable for presence of forest elephants in cell (IUCN)",
  "Mountain.Gorilla" = "Dummy variable for presence of mountain gorillas in cell (IUCN)",
  "Rhino" = "Dummy variable for presence of rhinos (black or white) in cell (IUCN)",
  "Elephant" = "Dummy variable for presence of elephants (African or forest) in cell (IUCN)",
  "num_big_game" = "Number of differnet spieces of big game - lions, leopards, elephants and cape buffalos",
  "Cls" = "Climate zone from the Köppen climate classification",
  "iso_a3" = "Alpha-3 country code",
  "colonial_origin" = "Colonial origin - from Hadenius et al. (2007)",
  "share_ranger" = "Share of rangers of PA staff in country, from Appleton et al. (2022)",
  "ranger_per_area" = "Number of rangers per PA area in country - from Appleton et al. (2022)",
  "forest_cover" = "Percentage of cell covered by trees in 2000 - from Hansen et al. (2013)",
  "mainmineral" = "Main mineral available in cell - from Berman et al. (2017)",
  "mines" = "Presence of mines in cell in 1997 - from Berman et al. (2017)",
  "majority_ethnic_neighbors_0_25" = "Dummy variable equal 1 if more than 25% of the cell neighbours are dominated by the same ethnic group",
  "majority_ethnic_neighbors_0_5" = "Dummy variable equal 1 if more than 50% of the cell neighbours are dominated by the same ethnic group",
  "majority_ethnic_neighbors_0_75" = "Dummy variable equal 1 if more than 75% of the cell neighbours are dominated by the same ethnic group",
  "majority_ethnic_neighbors_1" = "Dummy variable equal 1 if all of the cell neighbours are dominated by the same ethnic group",
  "gathering_geom" = "Dependence on gathering (0-9), matched by geometry - from Murdock et al. (1999)",
  "hunting_geom" = "Dependence on hunting (0-9), matched by geometry - from Murdock et al. (1999)",
  "fishing_geom" = "Dependence on fishing (0-9), matched by geometry - from Murdock et al. (1999)",
  "animal_husbandry_geom" = "Dependence on animal husbandry (0-9), matched by geometry - from Murdock et al. (1999)",
  "agriculture_geom" = "Dependence on agriculture (0-9), matched by geometry - from Murdock et al. (1999)",
  "gathering_text" = "Dependence on gathering (0-9), matched by name of ethnic group - from Murdock et al. (1999)",
  "hunting_text" = "Dependence on hunting (0-9), matched by name of ethnic group - from Murdock et al. (1999)",
  "fishing_text" = "Dependence on fishing (0-9), matched by name of ethnic group - from Murdock et al. (1999)",
  "animal_husbandry_text" = "Dependence on animal husbandry (0-9), matched by name of ethnic group - from Murdock et al. (1999)",
  "agriculture_text" = "Dependence on agriculture (0-9), matched by name of ethnic group - from Murdock et al. (1999)",
  "activity" = "Dominant activity for subsistence by ethnic group - from Murdock et al. (1999)",
  "arrivals" = "Number of tourists arriving in country in year - from World Tourism Organization",
  "receipts" = "Total expenditures by international inbound visitors (current USD) in country in year - from World Tourism Organization",
  "arrivals_pc" = "Ratio of tourists to population (country-year)",
  "receipts_pc" = "Tourist expendidures per local resident (country-year)",
  "arrivals_baseline" = "Number of tourists arriving in country in 1996",
  "arrivals_pc_baseline" = "Ratio of tourists to residents in country in 1996",
  "receipts_baseline" = "Tourist expendidures in country in 1996",
  "receipts_pc_baseline" = "Tourist expendidures per local resident in country in 1996",
  "Over5" = "Equal 1 if more than 5% of the cell is covered by PA",
  "Over10" = "Equal 1 if more than 10% of the cell is covered by PA",
  "Over20" = "Equal 1 if more than 20% of the cell is covered by PA",
  "Over30" = "Equal 1 if more than 30% of the cell is covered by PA",
  "Over40" = "Equal 1 if more than 40% of the cell is covered by PA",
  "Over50" = "Equal 1 if more than 50% of the cell is covered by PA",
  "Fatalities_dum" = "Equal 1 if there are any conflicts leading to fatalities (cell-year)",
  "Conflicts_dum" = "Equal 1 if there are any conflicts (cell-year)",
  "Fatalities_dum_state" = "Equal 1 if there are any conflicts involving the state leading to fatalities (cell-year)",
  "Fatalities_dum_non_state" = "Equal 1 if there are any conflicts only involving non-state actors leading to fatalities (cell-year)",
  "Fatalities_dum_jihad" = "Equal 1 if there are any conflicts involving Jihadist groups leading to fatalities (cell-year); Jihadist groups based on McGuirk and Nunn (2024)",
  "Fatalities_dum_non_jihad" = "Equal 1 if there are any conflicts only involving non-Jihadist groups leading to fatalities (cell-year); Jihadist groups based on McGuirk and Nunn (2024)",
  "Conflicts_dum_state" = "Equal 1 if there are any conflicts involving the state (cell-year)",
  "Conflicts_dum_non_state" = "Equal 1 if there are any conflicts only involving non-state actors (cell-year)",
  "Conflicts_dum_jihad" = "Equal 1 if there are any conflicts involving Jihadist groups (cell-year); Jihadist groups based on McGuirk and Nunn (2024)",
  "Conflicts_dum_non_jihad" = "Equal 1 if there are any conflicts only involving non-Jihadist groups (cell-year); Jihadist groups based on McGuirk and Nunn (2024)",
  "lpop" = "log of population",
  "lon" = "Longtitude of cell centroid",
  "lat" = "Latitude of cell centroid",
  "any_tree" = "Equal 1 if there is pterocarpus, diospyros or dalbergia in the cell",
  "climate" = "Groups of climate zones",
  "country_group" = "Regional country groups",
  "big_game" = "Equal 1 if there are lions, leopards, elephants or cape buffalos in the cell",
  "majority_nbors_diff" = "Equal 1 if more than 50% of the cell neighbours are from different ethnic groups",
  "above_tourism" = "Equal 1 if tourism (receipts per capita at baseline) is above average",
  "mean_precip" = "Average yearly percipitation in cell (based on 'precipitation' variable)",
  "sd_precip" = "Standard deviation of yearly precipitation in cell",
  "rainfall_shock" = "Equal 1 if yearly precipitation is below one SD of cell average",
  "hunting" = "Equal 1 if the ethnic group has more than 5% dependence on hunting",
  "gathering" = "Equal 1 if the ethnic group has more than 5% dependence on gathering",
  "animal_husbandry" = "Equal 1 if the ethnic group has more than 5% dependence on animal husbandry",
  "fishing" = "Equal 1 if the ethnic group has more than 5% dependence on fishing",
  "share_area_protected" = "Share of cell area covered by PAs",
  "total_events" = "Total number of violence against civilians and battles events (cell-year) from ACLED",
  "country" = "Based on the country with the largest share of the cell territory",
  "Cls-year" = "Climate-zone-year",
  "predicted_state_presence" = "Predicted state presence from Agneman et al. (2025), non-weighted average for values in each cell",
  "wdlf_indx_w" = "Wildlife watching species richness index from Capitani (2021), weighted by intersecting area",
  "wdlf_indx" = "Wildlife watching species richness index from Capitani (2021), weighted by intersecting area",
  "bird_watchers" = "Bird watchers from all origin countries (including Africa)",
  "bird_watchers_non_ssa" = "Bird watchers from all non-Sub-Saharan-African origin countries",
  "bird_watchers_usa" = "Bird watchers from the US",
  "bird_watchers_non_usa_ssa" = "Bird watchers from all non sub-Sahran-Africa origin countries, except the US"
)

labeled_data <- df %>%
  mutate(
    across(
      .cols = intersect(names(.), names(label_dict)),  # Only variables in dictionary
      .fns = ~labelled(., label = label_dict[[cur_column()]])
    )
  ) 

saveRDS(labeled_data, here(cln_dir, "data_with_labels.rds"))
write_dta(labeled_data, here(cln_dir, "event_for_stata.dta"))